version: '3.7'

services:
  parking-app:
    image: parking:5.0
    container_name: parking4_1
    ports:
      - ${SERVER_PORT:-8081}:8080
    volumes:
      - ./app/parking-web-1.0.0.jar:/app/parking-web-1.0.0.jar
      - ./rootfs:/rootfs
#      - ./init.sh:/usr/local/bin/init
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
    entrypoint: ["init"]
    restart: always
