version: '3.7'

services:
  parking-app:
    image: parking:4.0
    container_name: parking4_1
    ports:
      - 8084:8080
    volumes:
      - ./rootfs:/rootfs
      - ./rootfs/init.sh:/usr/local/bin/init
    restart: always
